services:
  # Next.js Widescreen Dashboard Web Application Container
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: delivery_dashboard_app
    restart: always
    ports:
      - "6010:6010"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      DATABASE_URL: "postgresql://asmita:asmita@postgres:5432/DeliveryDB"
      NEXT_PUBLIC_SHEET_URL: "https://docs.google.com/spreadsheets/d/19oxRDn6uiERIB97Jjz75aR2cEjzdWCFMWsnQJpDX2qg/edit?gid=0#gid=0"
      PORT: 6010
    networks:
      - infra

networks:
  infra:
    external: true
